server.port=5000

# URLs dos microsserviços
service.users.url=${USERS_URL:http://localhost:5001}
service.products.primary.url=${PRODUCTS_PRIMARY_URL:http://localhost:5002}
service.products.replica.url=${PRODUCTS_REPLICA_URL:http://localhost:5012}
service.orders.url=${ORDERS_URL:http://localhost:5003}

# Heartbeat: intervalo (ms) e máximo de falhas antes de marcar como DOWN
heartbeat.interval=5000
heartbeat.max-failures=2
